// Stable application error codes with fixed HTTP status mappings. Route
// handlers catch AppError and send { error: code, message } — raw
// database/DNS/XML-parser/HTTP-client errors never reach the response.

export type AppErrorCode =
  | 'PROJECT_NOT_FOUND'
  | 'PROJECT_SLUG_CONFLICT'
  | 'DOMAIN_NOT_FOUND'
  | 'DOMAIN_ALREADY_EXISTS'
  | 'DOMAIN_NOT_VERIFIED'
  | 'DOMAIN_VERIFICATION_FAILED'
  | 'DOMAIN_VERIFICATION_RATE_LIMITED'
  | 'DOMAIN_VERIFICATION_IN_PROGRESS'
  | 'VERIFICATION_TOKEN_INVALID'
  | 'SITEMAP_SOURCE_NOT_FOUND'
  | 'SITEMAP_NOT_FOUND'
  | 'SITEMAP_FETCH_FAILED'
  | 'SITEMAP_TOO_LARGE'
  | 'SITEMAP_PARSE_FAILED'
  | 'SITEMAP_LIMIT_EXCEEDED'
  | 'URL_DOMAIN_MISMATCH'
  | 'INVALID_DOMAIN'
  | 'INVALID_RENDER_URL'
  | 'DATABASE_UNAVAILABLE'
  | 'UNAUTHENTICATED'
  | 'FORBIDDEN'
  | 'FORBIDDEN_ROLE'
  | 'ORGANIZATION_NOT_FOUND'
  | 'MEMBER_NOT_FOUND'
  | 'ENDPOINT_MIGRATED'
  | 'CSRF_ORIGIN_REJECTED'
  | 'INVITATION_NOT_FOUND'
  | 'INVITATION_EXPIRED'
  | 'INVITATION_ALREADY_USED'
  | 'INVITATION_EMAIL_MISMATCH'
  | 'ACCOUNT_ALREADY_EXISTS'
  | 'RATE_LIMITED';

const STATUS_BY_CODE: Record<AppErrorCode, number> = {
  PROJECT_NOT_FOUND: 404,
  PROJECT_SLUG_CONFLICT: 409,
  DOMAIN_NOT_FOUND: 404,
  DOMAIN_ALREADY_EXISTS: 409,
  DOMAIN_NOT_VERIFIED: 409,
  DOMAIN_VERIFICATION_FAILED: 422,
  DOMAIN_VERIFICATION_RATE_LIMITED: 429,
  DOMAIN_VERIFICATION_IN_PROGRESS: 409,
  VERIFICATION_TOKEN_INVALID: 422,
  SITEMAP_SOURCE_NOT_FOUND: 404,
  SITEMAP_NOT_FOUND: 404,
  SITEMAP_FETCH_FAILED: 422,
  SITEMAP_TOO_LARGE: 422,
  SITEMAP_PARSE_FAILED: 422,
  SITEMAP_LIMIT_EXCEEDED: 422,
  URL_DOMAIN_MISMATCH: 400,
  INVALID_DOMAIN: 400,
  INVALID_RENDER_URL: 400,
  DATABASE_UNAVAILABLE: 503,
  UNAUTHENTICATED: 401,
  FORBIDDEN: 404, // cross-tenant access must not confirm resource existence
  FORBIDDEN_ROLE: 403, // confirmed member, insufficient role
  ORGANIZATION_NOT_FOUND: 404,
  MEMBER_NOT_FOUND: 404,
  ENDPOINT_MIGRATED: 410,
  CSRF_ORIGIN_REJECTED: 403,
  INVITATION_NOT_FOUND: 404,
  INVITATION_EXPIRED: 410,
  INVITATION_ALREADY_USED: 410,
  INVITATION_EMAIL_MISMATCH: 403,
  ACCOUNT_ALREADY_EXISTS: 409,
  RATE_LIMITED: 429,
};

export class AppError extends Error {
  readonly code: AppErrorCode;
  readonly statusCode: number;

  constructor(code: AppErrorCode, message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = 'AppError';
    this.code = code;
    this.statusCode = STATUS_BY_CODE[code];
  }
}

export function isAppError(err: unknown): err is AppError {
  return err instanceof AppError;
}
