#!/usr/bin/env bash
# Security smoke tests for hardened Docker compose
# Usage: bash scripts/security-smoke.sh
# Requires: docker, curl, jq
# Must be run with compose.hardened.yml already up and healthy.

set -Eeuo pipefail

COMPOSE_FILE="compose.hardened.yml"
# Set by CI to "compose.hardened-ci.yml" to layer in the TLS gateway
# profile (compose.hardened-ci.yml) — see .github/workflows/ci.yml. Empty
# by default, meaning only the base hardened file is used.
COMPOSE_OVERRIDE="${COMPOSE_OVERRIDE:-}"
RENDERER_SERVICE="renderer-api"
POSTGRES_SERVICE="postgres"
GATEWAY_SERVICE="gateway"
API_URL="${API_URL:-http://127.0.0.1:3000}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-}"
# True when running against the TLS-gateway profile (compose.hardened-ci.yml)
# instead of directly against renderer-api's loopback port.
TLS_MODE="${TLS_MODE:-false}"
# CA cert to verify the gateway's TLS certificate against, generated by
# docker/gateway/generate-ci-cert.sh. Never disable verification (no -k, no
# rejectUnauthorized:false) to make this pass instead.
CACERT="${CACERT:-}"
# Breaking change (Checkpoint 3B): no more global ADMIN_API_KEY/RENDER_API_KEY.
# This script bootstraps its own owner/org/project/domain/render-key below,
# using the non-interactive BOOTSTRAP_OWNER_PASSWORD fallback documented in
# scripts/auth/bootstrap-owner.ts (smoke/CI only, never production).
BOOTSTRAP_OWNER_PASSWORD="smoke-owner-$(openssl rand -hex 16)"
BOOTSTRAP_OWNER_EMAIL="smoke-owner@example.com"
# Must exactly match a configured AUTH_TRUSTED_ORIGINS entry — sent as the
# Origin header on cookie-authenticated mutations (see src/lib/csrf.ts).
BETTER_AUTH_BASE_URL="${BETTER_AUTH_BASE_URL:-http://localhost:3000}"
COOKIE_JAR="$(mktemp)"
trap 'rm -f "$COOKIE_JAR"' EXIT

PASS=0
FAIL=0
ERRORS=()

pass() { echo "  PASS: $1"; ((PASS++)) || true; }
fail() { echo "  FAIL: $1"; ((FAIL++)) || true; ERRORS+=("$1"); }
section() { echo ""; echo "=== $1 ==="; }

# All docker compose invocations below go through this so the TLS-gateway
# override (extra services/networks) is included whenever CI sets it,
# without having to touch every call site.
compose() {
  if [[ -n "$COMPOSE_OVERRIDE" ]]; then
    docker compose -f "$COMPOSE_FILE" -f "$COMPOSE_OVERRIDE" "$@"
  else
    docker compose -f "$COMPOSE_FILE" "$@"
  fi
}

# All curl calls below go through this wrapper so CACERT verification
# (against the CI-generated gateway CA) is applied uniformly instead of
# being duplicated at every call site, and so nothing ever needs -k /
# --insecure to pass.
curl() {
  if [[ -n "$CACERT" ]]; then
    command curl --cacert "$CACERT" "$@"
  else
    command curl "$@"
  fi
}

renderer_exec() {
  compose exec -T "$RENDERER_SERVICE" "$@" 2>/dev/null
}

get_container_id() {
  compose ps -q "$1" 2>/dev/null | head -1
}

# ---- Container Identity ----
section "Container Identity"

RENDERER_UID=$(renderer_exec id -u || echo "error")
if [[ "$RENDERER_UID" =~ ^[0-9]+$ && "$RENDERER_UID" -ne 0 ]]; then
  pass "Renderer UID is $RENDERER_UID (non-root)"
else
  fail "Renderer is running as root or could not determine UID ($RENDERER_UID)"
fi

# ---- Read-only Filesystem ----
section "Read-only Filesystem"

WRITE_RESULT=$(renderer_exec sh -c 'touch /should-not-write 2>&1; echo "exit:$?"' || echo "exit:error")
if echo "$WRITE_RESULT" | grep -qi "read-only\|permission denied" || [[ "$WRITE_RESULT" == *"exit:1"* ]]; then
  pass "Root filesystem is read-only"
else
  fail "Root filesystem appears writable"
fi

if renderer_exec sh -c 'touch /tmp/test-write && rm /tmp/test-write'; then
  pass "/tmp is writable"
else
  fail "/tmp is not writable"
fi

# ---- Docker Inspect ----
section "Container Security Configuration"

CONTAINER_ID=$(get_container_id "$RENDERER_SERVICE")
if [[ -z "$CONTAINER_ID" ]]; then
  fail "Could not find renderer container"
  # Skip inspect-dependent tests
else
  INSPECT=$(docker inspect "$CONTAINER_ID")

  if echo "$INSPECT" | jq -e '.[0].HostConfig.Privileged == false' > /dev/null 2>&1; then
    pass "privileged=false"
  else
    fail "Container may be privileged"
  fi

  if echo "$INSPECT" | jq -e '.[0].HostConfig.SecurityOpt // [] | map(select(contains("no-new-privileges"))) | length > 0' > /dev/null 2>&1; then
    pass "no-new-privileges is set"
  else
    fail "no-new-privileges not found"
  fi

  SECCOMP=$(echo "$INSPECT" | jq -r '.[0].HostConfig.SecurityOpt // [] | map(select(startswith("seccomp"))) | .[0] // "none"' 2>/dev/null)
  if [[ "$SECCOMP" != "none" ]]; then
    pass "Seccomp profile is set"
  else
    fail "No seccomp profile found"
  fi

  APPARMOR_OPT=$(echo "$INSPECT" | jq -r '.[0].AppArmorProfile // "none"' 2>/dev/null)
  if [[ "$APPARMOR_OPT" == "chromium-hardened" ]]; then
    pass "AppArmor profile is chromium-hardened (docker-default + userns,)"
  else
    fail "AppArmor profile is not chromium-hardened: $APPARMOR_OPT"
  fi

  if echo "$INSPECT" | jq -e '.[0].HostConfig.CapDrop // [] | index("ALL")' > /dev/null 2>&1; then
    pass "cap_drop ALL is set"
  else
    fail "cap_drop ALL not found"
  fi

  CAP_ADD=$(echo "$INSPECT" | jq -r '.[0].HostConfig.CapAdd // [] | length' 2>/dev/null)
  if [[ "$CAP_ADD" == "0" ]]; then
    pass "No capabilities added (no SYS_ADMIN)"
  else
    CAP_LIST=$(echo "$INSPECT" | jq -r '.[0].HostConfig.CapAdd // [] | join(",")' 2>/dev/null)
    fail "Capabilities added: $CAP_LIST"
  fi

  if echo "$INSPECT" | jq -e '.[0].HostConfig.ReadonlyRootfs == true' > /dev/null 2>&1; then
    pass "ReadonlyRootfs=true in inspect"
  else
    fail "ReadonlyRootfs not true in inspect"
  fi

  MEM_LIMIT=$(echo "$INSPECT" | jq -r '.[0].HostConfig.Memory // 0' 2>/dev/null)
  if [[ "$MEM_LIMIT" -gt 0 ]]; then
    pass "Memory limit set: $((MEM_LIMIT / 1024 / 1024)) MB"
  else
    fail "No memory limit"
  fi

  # CPU limit: check NanoCpus first, then CpuQuota
  CPU_NANO=$(echo "$INSPECT" | jq -r '.[0].HostConfig.NanoCpus // 0' 2>/dev/null)
  CPU_QUOTA=$(echo "$INSPECT" | jq -r '.[0].HostConfig.CpuQuota // 0' 2>/dev/null)
  if [[ "$CPU_NANO" -gt 0 ]]; then
    pass "CPU limit set via NanoCpus: $((CPU_NANO / 1000000000)) CPUs"
  elif [[ "$CPU_QUOTA" -gt 0 ]]; then
    pass "CPU limit set via CpuQuota: $CPU_QUOTA"
  else
    fail "No CPU limit"
  fi

  PID_LIMIT=$(echo "$INSPECT" | jq -r '.[0].HostConfig.PidsLimit // 0' 2>/dev/null)
  if [[ "$PID_LIMIT" -gt 0 ]]; then
    pass "PID limit set: $PID_LIMIT"
  else
    fail "No PID limit"
  fi

  # Check no Docker socket mount
  DOCKER_SOCK=$(echo "$INSPECT" | jq -r '[.[0].Mounts // [] | .[] | select(.Source | contains("docker.sock"))] | length' 2>/dev/null)
  if [[ "$DOCKER_SOCK" == "0" ]]; then
    pass "No Docker socket mount"
  else
    fail "Docker socket is mounted"
  fi

  # Check renderer networks
  NETWORKS=$(echo "$INSPECT" | jq -r '.[0].NetworkSettings.Networks // {} | keys[]' 2>/dev/null)
  echo "  INFO: Renderer networks: $NETWORKS"
fi

# Check proxy has no published host ports
section "Proxy Port Exposure"

PROXY_ID=$(get_container_id "egress-proxy")
if [[ -n "$PROXY_ID" ]]; then
  PROXY_PORTS=$(docker inspect "$PROXY_ID" | jq -r '.[0].HostConfig.PortBindings // {} | keys[]' 2>/dev/null || echo "")
  if [[ -z "$PROXY_PORTS" ]]; then
    pass "Proxy has no published ports"
  else
    fail "Proxy has published ports: $PROXY_PORTS"
  fi
else
  fail "Could not find proxy container"
fi

# ---- Direct Egress ----
section "Direct Internet Egress"

# Note: With internal:true network, direct egress is blocked at Docker level.
# Without internal:true, the renderer relies on proxy configuration and
# application-level SSRF controls. This test checks if Chromium traffic
# goes through the proxy (verified by the proxy access tests below).

# ---- Chromium Sandbox ----
section "Chromium Sandbox"

echo "  INFO: Kernel: $(renderer_exec uname -a 2>/dev/null || echo unknown)"
echo "  INFO: Docker version: $(docker version --format '{{.Server.Version}}' 2>/dev/null || echo unknown)"
echo "  INFO: Container UID/GID: $(renderer_exec sh -c 'id' 2>/dev/null || echo unknown)"
echo "  INFO: unprivileged_userns_clone: $(renderer_exec cat /proc/sys/kernel/unprivileged_userns_clone 2>/dev/null || echo 'n/a (not exposed in container)')"
echo "  INFO: max_user_namespaces: $(renderer_exec cat /proc/sys/user/max_user_namespaces 2>/dev/null || echo 'n/a (not exposed in container)')"
echo "  INFO: Seccomp profile path: docker/security/chromium-seccomp.json"
echo "  INFO: Live AppArmor label: $(renderer_exec cat /proc/self/attr/current 2>/dev/null || echo unknown)"
echo "  INFO: Raw unshare --user test: $(renderer_exec sh -c 'unshare --user --map-root-user id 2>&1' || echo failed)"

SANDBOX_CHECK=$(renderer_exec node -e "
import('playwright').then(async ({ chromium }) => {
  const fs = await import('node:fs/promises');
  const browser = await chromium.launch({
    headless: true,
    chromiumSandbox: true,
    args: ['--disable-dev-shm-usage', '--disable-extensions', '--disable-background-networking', '--no-first-run'],
  });
  console.log('LAUNCH_OK');

  let cmdlines = [];
  try {
    const pids = await fs.readdir('/proc');
    for (const pid of pids) {
      if (!/^[0-9]+$/.test(pid) || Number(pid) === process.pid) continue;
      try {
        const raw = await fs.readFile('/proc/' + pid + '/cmdline', 'utf8');
        if (raw.includes('chrome-headless-shell')) cmdlines.push(raw.replace(/\x00/g, ' ').trim());
      } catch {}
    }
  } catch {}
  console.log('CMDLINE_COUNT:' + cmdlines.length);
  console.log('CMDLINE_ONE:' + (cmdlines[0] || '').slice(0, 200));
  const noSandboxMatch = cmdlines.find((c) => c.includes('--no-sandbox'));
  const setuidMatch = cmdlines.find((c) => c.includes('--disable-setuid-sandbox'));
  console.log('CMDLINE_HAS_NO_SANDBOX:' + !!noSandboxMatch);
  console.log('CMDLINE_HAS_DISABLE_SETUID:' + !!setuidMatch);
  if (noSandboxMatch) console.log('MATCH_NO_SANDBOX:' + noSandboxMatch.slice(0, 400));
  if (setuidMatch) console.log('MATCH_SETUID:' + setuidMatch.slice(0, 400));

  const page = await browser.newPage();
  await page.goto('https://example.com', { waitUntil: 'networkidle', timeout: 15000 });
  const title = await page.title();
  console.log('RENDER_OK:' + title);
  await browser.close();
  console.log('CLOSE_OK');
}).catch((e) => { console.log('LAUNCH_FAIL:' + e.message); process.exit(1); });
" 2>&1) || true

if echo "$SANDBOX_CHECK" | grep -q "LAUNCH_OK"; then
  pass "Chromium launched with chromiumSandbox=true"
else
  fail "Chromium sandbox launch failed"
  echo "  DETAIL: $SANDBOX_CHECK"
fi

if echo "$SANDBOX_CHECK" | grep -q "RENDER_OK"; then
  pass "Sandboxed render succeeded ($(echo "$SANDBOX_CHECK" | grep -o 'RENDER_OK:.*'))"
else
  fail "Sandboxed render did not complete"
fi

if echo "$SANDBOX_CHECK" | grep -q "CLOSE_OK"; then
  pass "Sandboxed browser closed cleanly"
else
  fail "Sandboxed browser did not close cleanly"
fi

if echo "$SANDBOX_CHECK" | grep -q "CMDLINE_HAS_NO_SANDBOX:false" && \
   echo "$SANDBOX_CHECK" | grep -q "CMDLINE_HAS_DISABLE_SETUID:false"; then
  pass "No forbidden sandbox-bypass flags on live Chromium command line"
else
  fail "Forbidden sandbox-bypass flag found on live Chromium command line"
  echo "  DEBUG: $(echo "$SANDBOX_CHECK" | grep -E 'CMDLINE_HAS|CMDLINE_ONE:|MATCH_NO_SANDBOX|MATCH_SETUID')"
fi

echo "  INFO: $(echo "$SANDBOX_CHECK" | grep -o 'CMDLINE_COUNT:.*')"

# No lingering Chromium processes after the sandbox check closes its browser.
# The `sh -c` wrapper's own /proc/$$/cmdline contains this entire script's
# source text (including both grep substrings), so it must be excluded by
# path -- not just by splitting into separate single-substring greps, since
# the outer sh process's single argv still contains both substrings together.
sleep 3
LEFTOVER=$(renderer_exec sh -c 'self=/proc/$$/cmdline; count=0; for f in /proc/[0-9]*/cmdline; do [ "$f" = "$self" ] && continue; grep -q ms-playwright "$f" 2>/dev/null && grep -q chrome-headless-shell "$f" 2>/dev/null && count=$((count+1)); done; echo $count' 2>/dev/null || echo "0")
LEFTOVER="${LEFTOVER//[[:space:]]/}"
if [[ "$LEFTOVER" =~ ^[0-9]+$ ]] && [[ "$LEFTOVER" -eq 0 ]]; then
  pass "No leftover Chromium processes after sandboxed launch"
else
  fail "Leftover Chromium processes detected: $LEFTOVER"
  renderer_exec sh -c 'self=/proc/$$/cmdline; for f in /proc/[0-9]*/cmdline; do [ "$f" = "$self" ] && continue; grep -q ms-playwright "$f" 2>/dev/null && grep -q chrome-headless-shell "$f" 2>/dev/null && { echo "  DEBUG: $f:"; tr "\0" " " < "$f"; echo; }; done' || true
fi

# Restart/recovery: the renderer must be able to launch a fresh sandboxed
# browser again after the previous one closed (simulates crash recovery).
RECOVERY_CHECK=$(renderer_exec node -e "
import('playwright').then(async ({ chromium }) => {
  const browser = await chromium.launch({ headless: true, chromiumSandbox: true });
  const page = await browser.newPage();
  await page.goto('https://example.com', { waitUntil: 'networkidle', timeout: 15000 });
  console.log('RECOVERY_OK:' + (await page.title()));
  await browser.close();
}).catch((e) => console.log('RECOVERY_FAIL:' + e.message));
" 2>&1) || true
if echo "$RECOVERY_CHECK" | grep -q "RECOVERY_OK"; then
  pass "Sandboxed browser can relaunch after previous instance closed"
else
  fail "Sandboxed browser failed to relaunch: $RECOVERY_CHECK"
fi

# chrome://sandbox is not reliably readable in headless mode; this is
# informational only and does not gate pass/fail. The authoritative signals
# are: successful sandboxed launch above, chromiumSandbox=true, absence of
# --no-sandbox/--disable-setuid-sandbox on the live process, active seccomp
# profile, and non-root UID (all checked above/elsewhere in this script).
SANDBOX_PAGE=$(renderer_exec node -e "
import('playwright').then(async ({ chromium }) => {
  const browser = await chromium.launch({ headless: true, chromiumSandbox: true });
  const page = await browser.newPage();
  await page.goto('chrome://sandbox', { timeout: 5000 }).catch(() => {});
  const text = await page.content().catch(() => '');
  console.log(text.replace(/\n/g, ' ').slice(0, 500));
  await browser.close();
}).catch((e) => console.log('UNREADABLE:' + e.message));
" 2>&1) || true
if [[ -z "$SANDBOX_PAGE" || "$SANDBOX_PAGE" == UNREADABLE* ]]; then
  echo "  INFO: chrome://sandbox not readable in headless mode (expected) — relying on launch/cmdline/seccomp/UID evidence above instead."
else
  echo "  INFO: chrome://sandbox output (best-effort): ${SANDBOX_PAGE:0:300}"
fi

# ---- Proxy Public Access ----
section "Proxy Public Internet Access"

PUBLIC_HTTP_OK=false
for attempt in 1 2 3; do
  if renderer_exec node -e "
    fetch('http://example.com/', { signal: AbortSignal.timeout(15000) })
      .then(r => { if (r.ok) process.exit(0); else process.exit(1); })
      .catch(() => process.exit(1));
  " 2>/dev/null; then
    PUBLIC_HTTP_OK=true
    break
  fi
  sleep 2
done
if $PUBLIC_HTTP_OK; then
  pass "Public HTTP via proxy works"
else
  fail "Public HTTP via proxy failed (3 attempts)"
fi

PUBLIC_HTTPS_OK=false
for attempt in 1 2 3; do
  if renderer_exec node -e "
    fetch('https://example.com/', { signal: AbortSignal.timeout(15000) })
      .then(r => { if (r.ok) process.exit(0); else process.exit(1); })
      .catch(() => process.exit(1));
  " 2>/dev/null; then
    PUBLIC_HTTPS_OK=true
    break
  fi
  sleep 2
done
if $PUBLIC_HTTPS_OK; then
  pass "Public HTTPS via proxy works"
else
  fail "Public HTTPS via proxy failed (3 attempts)"
fi

# ---- Private Destination Blocking ----
section "Private Destination Blocking (via proxy)"

BLOCKED_TARGETS=(
  "http://127.0.0.1/"
  "http://localhost/"
  "http://10.0.0.1/"
  "http://169.254.169.254/latest/meta-data/"
  "http://metadata.google.internal/"
  "http://renderer-api:3000/"
  "http://egress-proxy:3128/"
)

for target in "${BLOCKED_TARGETS[@]}"; do
  RESULT=$(renderer_exec node -e "
    fetch('${target}', { signal: AbortSignal.timeout(5000) })
      .then(r => { console.log('status:' + r.status); process.exit(r.ok ? 1 : 0); })
      .catch(() => { console.log('blocked'); process.exit(0); });
  " 2>/dev/null; echo "exit:$?")

  if [[ "$RESULT" == *"exit:0"* ]]; then
    pass "Blocked: $target"
  else
    fail "NOT blocked: $target"
  fi
done

# ---- Non-standard Port Blocking ----
section "Non-standard Port Blocking (via proxy)"

BLOCKED_PORTS=(22 3000 3306 5432 6379 8080)
for port in "${BLOCKED_PORTS[@]}"; do
  RESULT=$(renderer_exec node -e "
    fetch('http://example.com:${port}/', { signal: AbortSignal.timeout(5000) })
      .then(r => { console.log('status:' + r.status); process.exit(r.ok ? 1 : 0); })
      .catch(() => { console.log('blocked'); process.exit(0); });
  " 2>/dev/null; echo "exit:$?")

  if [[ "$RESULT" == *"exit:0"* ]]; then
    pass "Port $port blocked"
  else
    fail "Port $port NOT blocked"
  fi
done

# ---- Renderer API (bootstrap-owner -> session -> org-scoped project-key render) ----
section "Renderer API (project-scoped key flow)"

HEALTH=$(curl -sf --connect-timeout 5 --max-time 10 "$API_URL/health" 2>/dev/null || echo '{"error":"timeout"}')
if echo "$HEALTH" | jq -e '.status == "ok"' > /dev/null 2>&1; then
  pass "/health returns ok"
else
  fail "/health failed: $HEALTH"
fi

# 1. Bootstrap the first owner (non-interactive fallback documented in
# scripts/auth/bootstrap-owner.ts — smoke/CI only).
BOOTSTRAP_OUT=$(compose exec -T \
  -e BOOTSTRAP_OWNER_PASSWORD="$BOOTSTRAP_OWNER_PASSWORD" \
  "$RENDERER_SERVICE" node dist/scripts/auth/bootstrap-owner.js \
  --email="$BOOTSTRAP_OWNER_EMAIL" --name="Smoke Owner" --org-name="Smoke Org" 2>&1) || true
if echo "$BOOTSTRAP_OUT" | grep -q "Owner bootstrap complete"; then
  pass "auth:bootstrap-owner creates the first user + organization"
else
  fail "bootstrap-owner failed: $(echo "$BOOTSTRAP_OUT" | head -c 300)"
fi

# 2. Login and obtain a session cookie.
LOGIN_STATUS=$(curl -s -o /dev/null -w '%{http_code}' -c "$COOKIE_JAR" --connect-timeout 5 --max-time 10 \
  -X POST "$API_URL/api/auth/sign-in/email" \
  -H "content-type: application/json" \
  -d "{\"email\":\"$BOOTSTRAP_OWNER_EMAIL\",\"password\":\"$BOOTSTRAP_OWNER_PASSWORD\"}" 2>/dev/null || echo "000")
if [[ "$LOGIN_STATUS" == "200" ]] && grep -q "session_token" "$COOKIE_JAR" 2>/dev/null; then
  pass "Login succeeds and a session cookie is obtained"
else
  fail "Login failed (status $LOGIN_STATUS) or no session cookie set"
fi

ORG_LIST=$(curl -sf -b "$COOKIE_JAR" --connect-timeout 5 --max-time 10 "$API_URL/v1/organizations" 2>/dev/null || echo '{}')
ORG_ID=$(echo "$ORG_LIST" | jq -r '.items[0].id // empty')
if [[ -n "$ORG_ID" ]]; then
  pass "GET /v1/organizations returns the bootstrapped organization"
else
  fail "Could not resolve organization id: $(echo "$ORG_LIST" | head -c 200)"
fi

# 3. Create an organization-scoped project.
PROJECT_RESPONSE=$(curl -sf -b "$COOKIE_JAR" --connect-timeout 5 --max-time 10 -X POST "$API_URL/v1/organizations/$ORG_ID/projects" \
  -H "content-type: application/json" -H "origin: $BETTER_AUTH_BASE_URL" \
  -d '{"name":"Smoke Test Project"}' 2>/dev/null || echo '{"error":"timeout"}')
PROJECT_ID=$(echo "$PROJECT_RESPONSE" | jq -r '.id // empty')
if [[ -n "$PROJECT_ID" ]]; then
  pass "POST .../projects creates an organization-scoped project"
else
  fail "POST .../projects failed: $(echo "$PROJECT_RESPONSE" | head -c 200)"
fi

# 4. Create + verify the fixture domain (DNS TXT verification isn't
# available for a real hostname in CI, so this marks it verified directly
# via SQL — a test-only shortcut, not a substitute for the DNS/HTML
# verification unit+db tests).
DOMAIN_RESPONSE=$(curl -sf -b "$COOKIE_JAR" --connect-timeout 5 --max-time 10 -X POST "$API_URL/v1/organizations/$ORG_ID/projects/$PROJECT_ID/domains" \
  -H "content-type: application/json" -H "origin: $BETTER_AUTH_BASE_URL" \
  -d '{"hostname":"example.com","verificationMethod":"dns_txt"}' 2>/dev/null || echo '{"error":"timeout"}')
DOMAIN_ID=$(echo "$DOMAIN_RESPONSE" | jq -r '.domain.id // empty')
if [[ -n "$DOMAIN_ID" ]] && echo "$DOMAIN_RESPONSE" | jq -e '.verification.token // "" | length > 0' > /dev/null 2>&1; then
  pass "POST domain creates a pending domain with a one-time verification token"
else
  fail "POST domain failed: $(echo "$DOMAIN_RESPONSE" | head -c 200)"
fi

if [[ -n "$POSTGRES_PASSWORD" ]]; then
  compose exec -T "$POSTGRES_SERVICE" \
    psql -U prerender -d prerender -c \
    "UPDATE domains SET status='verified', verified_at=now() WHERE id='$DOMAIN_ID'" > /dev/null 2>&1 || true
fi
VERIFIED_CHECK=$(curl -sf -b "$COOKIE_JAR" --connect-timeout 5 --max-time 10 "$API_URL/v1/organizations/$ORG_ID/domains/$DOMAIN_ID" 2>/dev/null || echo '{}')
if echo "$VERIFIED_CHECK" | jq -e '.status == "verified"' > /dev/null 2>&1; then
  pass "Domain marked verified (test-only DB shortcut) for render authorization check"
else
  fail "Could not mark domain verified for smoke test: $(echo "$VERIFIED_CHECK" | head -c 200)"
fi

# 5. Create the project-scoped render API key.
KEY_RESPONSE=$(curl -sf -b "$COOKIE_JAR" --connect-timeout 5 --max-time 10 -X POST "$API_URL/v1/organizations/$ORG_ID/projects/$PROJECT_ID/api-keys" \
  -H "content-type: application/json" -H "origin: $BETTER_AUTH_BASE_URL" \
  -d '{"name":"Smoke Key"}' 2>/dev/null || echo '{"error":"timeout"}')
RENDER_API_KEY=$(echo "$KEY_RESPONSE" | jq -r '.key // empty')
API_KEY_ID=$(echo "$KEY_RESPONSE" | jq -r '.id // empty')
if [[ -n "$RENDER_API_KEY" && "$RENDER_API_KEY" == pr_live_* ]]; then
  pass "Project API key created with pr_live_ prefix, plaintext shown once"
else
  fail "Project API key creation failed: $(echo "$KEY_RESPONSE" | head -c 200)"
fi

# 6. Render a real page with the project-scoped key.
RENDER=$(curl -sf --connect-timeout 10 --max-time 30 -X POST "$API_URL/v1/render" \
  -H "content-type: application/json" \
  -H "x-render-api-key: $RENDER_API_KEY" \
  -d "{\"domainId\":\"$DOMAIN_ID\",\"url\":\"https://example.com\"}" 2>/dev/null || echo '{"error":"timeout"}')

if echo "$RENDER" | jq -e '.html | length > 100' > /dev/null 2>&1; then
  TITLE=$(echo "$RENDER" | jq -r '.title // "unknown"')
  pass "Render successful for verified domain with project-scoped key — title: $TITLE"
else
  fail "Render failed for verified domain: $(echo "$RENDER" | head -c 200)"
fi

# 7. Cross-project render rejected: a key from a second project must not
# render the first project's domain.
PROJECT2_RESPONSE=$(curl -sf -b "$COOKIE_JAR" --connect-timeout 5 --max-time 10 -X POST "$API_URL/v1/organizations/$ORG_ID/projects" \
  -H "content-type: application/json" -H "origin: $BETTER_AUTH_BASE_URL" \
  -d '{"name":"Smoke Test Project 2"}' 2>/dev/null || echo '{}')
PROJECT2_ID=$(echo "$PROJECT2_RESPONSE" | jq -r '.id // empty')
KEY2_RESPONSE=$(curl -sf -b "$COOKIE_JAR" --connect-timeout 5 --max-time 10 -X POST "$API_URL/v1/organizations/$ORG_ID/projects/$PROJECT2_ID/api-keys" \
  -H "content-type: application/json" -H "origin: $BETTER_AUTH_BASE_URL" \
  -d '{"name":"Smoke Key 2"}' 2>/dev/null || echo '{}')
RENDER_API_KEY_2=$(echo "$KEY2_RESPONSE" | jq -r '.key // empty')
CROSS_PROJECT_RENDER=$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 --max-time 10 -X POST "$API_URL/v1/render" \
  -H "content-type: application/json" \
  -H "x-render-api-key: $RENDER_API_KEY_2" \
  -d "{\"domainId\":\"$DOMAIN_ID\",\"url\":\"https://example.com\"}" 2>/dev/null || echo "000")
if [[ "$CROSS_PROJECT_RENDER" == "404" ]]; then
  pass "Cross-project render rejected (404, key from project 2 cannot render project 1's domain)"
else
  fail "Cross-project render returned $CROSS_PROJECT_RENDER, expected 404"
fi

UNVERIFIED_DOMAIN_RESPONSE=$(curl -sf -b "$COOKIE_JAR" --connect-timeout 5 --max-time 10 -X POST "$API_URL/v1/organizations/$ORG_ID/projects/$PROJECT_ID/domains" \
  -H "content-type: application/json" -H "origin: $BETTER_AUTH_BASE_URL" \
  -d '{"hostname":"unverified-smoke.example.com","verificationMethod":"dns_txt"}' 2>/dev/null || echo '{"error":"timeout"}')
UNVERIFIED_DOMAIN_ID=$(echo "$UNVERIFIED_DOMAIN_RESPONSE" | jq -r '.domain.id // empty')
UNVERIFIED_RENDER=$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 --max-time 10 -X POST "$API_URL/v1/render" \
  -H "content-type: application/json" \
  -H "x-render-api-key: $RENDER_API_KEY" \
  -d "{\"domainId\":\"$UNVERIFIED_DOMAIN_ID\",\"url\":\"https://unverified-smoke.example.com\"}" 2>/dev/null || echo "000")
if [[ "$UNVERIFIED_RENDER" == "409" ]]; then
  pass "Render rejected for unverified domain (409 DOMAIN_NOT_VERIFIED)"
else
  fail "Render on unverified domain returned $UNVERIFIED_RENDER, expected 409"
fi

# 8. Confirm old global-key / legacy-header behavior fails.
OLD_HEADER_RENDER=$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 --max-time 10 -X POST "$API_URL/v1/render" \
  -H "content-type: application/json" \
  -H "x-api-key: $RENDER_API_KEY" \
  -d "{\"domainId\":\"$DOMAIN_ID\",\"url\":\"https://example.com\"}" 2>/dev/null || echo "000")
if [[ "$OLD_HEADER_RENDER" == "401" ]]; then
  pass "Legacy x-api-key header no longer authenticates /v1/render"
else
  fail "Legacy x-api-key header returned $OLD_HEADER_RENDER, expected 401"
fi

OLD_ADMIN_MGMT=$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 --max-time 10 -X POST "$API_URL/v1/projects" \
  -H "content-type: application/json" \
  -H "x-admin-api-key: any-value-whatsoever" \
  -d '{"name":"x"}' 2>/dev/null || echo "000")
if [[ "$OLD_ADMIN_MGMT" == "410" ]]; then
  pass "Legacy unscoped management endpoint returns 410 (x-admin-api-key grants nothing)"
else
  fail "Legacy management endpoint returned $OLD_ADMIN_MGMT, expected 410"
fi

# 9. Revoke the key.
REVOKE_STATUS=$(curl -s -o /dev/null -w '%{http_code}' -b "$COOKIE_JAR" --connect-timeout 5 --max-time 10 \
  -X DELETE "$API_URL/v1/organizations/$ORG_ID/projects/$PROJECT_ID/api-keys/$API_KEY_ID" \
  -H "origin: $BETTER_AUTH_BASE_URL" 2>/dev/null || echo "000")
if [[ "$REVOKE_STATUS" == "200" ]]; then
  pass "Render API key revoked"
else
  fail "Key revoke returned $REVOKE_STATUS, expected 200"
fi

# 10. Confirm the revoked key fails.
REVOKED_RENDER=$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 --max-time 10 -X POST "$API_URL/v1/render" \
  -H "content-type: application/json" \
  -H "x-render-api-key: $RENDER_API_KEY" \
  -d "{\"domainId\":\"$DOMAIN_ID\",\"url\":\"https://example.com\"}" 2>/dev/null || echo "000")
if [[ "$REVOKED_RENDER" == "401" ]]; then
  pass "Revoked key rejected (401)"
else
  fail "Revoked key returned $REVOKED_RENDER, expected 401"
fi

# 11. Logout, then confirm the logged-out session is rejected.
curl -s -o /dev/null -b "$COOKIE_JAR" --connect-timeout 5 --max-time 10 -X POST "$API_URL/api/auth/sign-out" > /dev/null 2>&1 || true
LOGGED_OUT_STATUS=$(curl -s -o /dev/null -w '%{http_code}' -b "$COOKIE_JAR" --connect-timeout 5 --max-time 10 "$API_URL/v1/organizations" 2>/dev/null || echo "000")
if [[ "$LOGGED_OUT_STATUS" == "401" ]]; then
  pass "Logged-out session is rejected on the next management request"
else
  fail "Logged-out session returned $LOGGED_OUT_STATUS, expected 401"
fi

# ---- Observability ----
section "Observability"

LIVEZ=$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 --max-time 10 "$API_URL/livez" 2>/dev/null || echo "000")
if [[ "$LIVEZ" == "200" ]]; then
  pass "/livez returns 200"
else
  fail "/livez returned $LIVEZ"
fi

READYZ=$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 --max-time 10 "$API_URL/readyz" 2>/dev/null || echo "000")
if [[ "$READYZ" == "200" ]]; then
  pass "/readyz returns 200"
else
  fail "/readyz returned $READYZ"
fi

if [[ "$TLS_MODE" == "true" ]]; then
  # With the TLS gateway profile, renderer-api publishes no host port at
  # all — the gateway (docker/gateway/nginx-tls.conf) is the only path in
  # from $API_URL, and it hard-returns 404 for /metrics without ever
  # reaching renderer-api. This is the real public-facing boundary check
  # that the non-TLS profile below can only document, not exercise.
  METRICS_HTTP=$(curl -s -o /tmp/metrics-response.txt -w '%{http_code}' --connect-timeout 5 --max-time 10 "$API_URL/metrics" 2>/dev/null || echo "000")
  if [[ "$METRICS_HTTP" == "404" ]]; then
    pass "/metrics returns 404 through the public-facing TLS gateway"
  else
    fail "/metrics returned $METRICS_HTTP through the gateway, expected 404"
  fi
else
  # NOTE on "public gateway blocks /metrics": this MVP has no separate
  # public gateway container in the base (non-TLS) profile (see
  # docker/gateway/nginx.conf header comment) — renderer-api is published
  # only to 127.0.0.1, so it is not reachable from the public internet by
  # construction. The check below exercises the actual boundary that
  # exists in that profile: the app-level private/loopback guard in
  # src/routes/metrics.ts. curl from this CI runner arrives as loopback,
  # so it is expected to be ALLOWED — this documents current behavior
  # rather than simulating public internet access, which this topology
  # cannot do. The TLS profile above tests the real public boundary.
  METRICS_HTTP=$(curl -s -o /tmp/metrics-response.txt -w '%{http_code}' --connect-timeout 5 --max-time 10 "$API_URL/metrics" 2>/dev/null || echo "000")
  if [[ "$METRICS_HTTP" == "200" ]]; then
    pass "/metrics reachable from host-published loopback port (127.0.0.1) — expected, no public gateway exists in this profile"
  else
    fail "/metrics unexpectedly returned $METRICS_HTTP from loopback"
  fi

  METRICS_CONTENT_TYPE=$(curl -s -D - -o /dev/null --connect-timeout 5 --max-time 10 "$API_URL/metrics" 2>/dev/null | grep -i '^content-type:' || echo "")
  if echo "$METRICS_CONTENT_TYPE" | grep -qi 'text/plain'; then
    pass "/metrics returns Prometheus text content type"
  else
    fail "/metrics content-type unexpected: $METRICS_CONTENT_TYPE"
  fi
fi

METRICS_INTERNAL=$(renderer_exec sh -c 'wget -qO- http://localhost:3000/metrics 2>/dev/null || curl -sf http://localhost:3000/metrics 2>/dev/null' || echo "")
if echo "$METRICS_INTERNAL" | grep -q '^# HELP prerender_'; then
  pass "/metrics reachable from inside the renderer container (internal network path)"
else
  fail "/metrics not reachable from inside the renderer container"
fi

if echo "$METRICS_INTERNAL" | grep -q 'prerender_render_requests_total{result="success"}'; then
  SUCCESS_COUNT=$(echo "$METRICS_INTERNAL" | grep 'prerender_render_requests_total{result="success"}' | awk '{print $2}')
  if [[ -n "$SUCCESS_COUNT" ]] && [[ "$SUCCESS_COUNT" != "0" ]]; then
    pass "Render success metric increased after real render (count=$SUCCESS_COUNT)"
  else
    fail "Render success metric present but zero after a successful render"
  fi
else
  fail "Render success metric not found after a successful render"
fi

if echo "$METRICS_INTERNAL" | grep -qF "$RENDER_API_KEY"; then
  fail "Metrics output contains an API key"
else
  pass "Metrics output does not contain an API key"
fi

if echo "$METRICS_INTERNAL" | grep -qE 'https?://|url="'; then
  fail "Metrics output contains a raw URL"
else
  pass "Metrics output does not contain a raw URL or query string"
fi

# ---- Container Log Hygiene ----
section "Container Log Hygiene"

RENDERER_LOGS=$(compose logs "$RENDERER_SERVICE" 2>/dev/null || echo "")

if echo "$RENDERER_LOGS" | grep -qF "$RENDER_API_KEY"; then
  fail "Renderer container logs contain an API key"
else
  pass "Renderer container logs do not contain an API key"
fi

if echo "$RENDERER_LOGS" | grep -qE '\?[a-zA-Z0-9_]+=|query=|token='; then
  fail "Renderer container logs may contain a query string"
else
  pass "Renderer container logs do not contain a query string"
fi

DOCKER_HEALTH=$(docker inspect "$(get_container_id "$RENDERER_SERVICE")" | jq -r '.[0].State.Health.Status // "none"' 2>/dev/null)
if [[ "$DOCKER_HEALTH" == "healthy" ]]; then
  pass "Docker healthcheck (via /readyz) reports healthy"
else
  fail "Docker healthcheck status: $DOCKER_HEALTH"
fi

# ---- Database ----
section "Database"

POSTGRES_ID=$(get_container_id "$POSTGRES_SERVICE")
if [[ -n "$POSTGRES_ID" ]]; then
  PG_INSPECT=$(docker inspect "$POSTGRES_ID")

  PG_PORTS=$(echo "$PG_INSPECT" | jq -r '.[0].HostConfig.PortBindings // {} | keys[]' 2>/dev/null || echo "")
  if [[ -z "$PG_PORTS" ]]; then
    pass "PostgreSQL has no published host ports"
  else
    fail "PostgreSQL has published ports: $PG_PORTS"
  fi

  PG_NETWORKS=$(echo "$PG_INSPECT" | jq -r '.[0].NetworkSettings.Networks // {} | keys[]' 2>/dev/null)
  if echo "$PG_NETWORKS" | grep -q '_external$\|^external$'; then
    fail "PostgreSQL is attached to the external (internet-facing) network: $PG_NETWORKS"
  else
    pass "PostgreSQL is not attached to the external network (networks: $(echo "$PG_NETWORKS" | tr '\n' ' '))"
  fi

  PG_CAPADD=$(echo "$PG_INSPECT" | jq -r '.[0].HostConfig.CapAdd // [] | index("SYS_ADMIN")')
  if [[ "$PG_CAPADD" == "null" ]]; then
    pass "PostgreSQL does not have SYS_ADMIN capability"
  else
    fail "PostgreSQL has SYS_ADMIN capability"
  fi
else
  fail "Could not find postgres container"
fi

# Readiness must react to the database actually being down, and /livez must
# stay 200 throughout (liveness is process-only, never DB-dependent).
compose stop "$POSTGRES_SERVICE" > /dev/null 2>&1 || true
sleep 4

LIVEZ_DURING_DB_DOWN=$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 --max-time 10 "$API_URL/livez" 2>/dev/null || echo "000")
if [[ "$LIVEZ_DURING_DB_DOWN" == "200" ]]; then
  pass "/livez stays 200 while database is down"
else
  fail "/livez returned $LIVEZ_DURING_DB_DOWN while database is down"
fi

READYZ_DURING_DB_DOWN=$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 --max-time 10 "$API_URL/readyz" 2>/dev/null || echo "000")
if [[ "$READYZ_DURING_DB_DOWN" == "503" ]]; then
  pass "/readyz returns 503 while database is down"
else
  fail "/readyz returned $READYZ_DURING_DB_DOWN while database is down (expected 503)"
fi

compose start "$POSTGRES_SERVICE" > /dev/null 2>&1 || true
READYZ_RECOVERED=false
for _ in $(seq 1 15); do
  CODE=$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 --max-time 10 "$API_URL/readyz" 2>/dev/null || echo "000")
  if [[ "$CODE" == "200" ]]; then
    READYZ_RECOVERED=true
    break
  fi
  sleep 2
done
if $READYZ_RECOVERED; then
  pass "/readyz returns 200 again after database recovers (restart + volume behavior confirmed)"
else
  fail "/readyz did not recover to 200 after restarting the database"
fi

# ---- TLS Gateway ----
if [[ "$TLS_MODE" == "true" ]]; then
  section "TLS Gateway"

  RENDERER_NODE_ENV=$(renderer_exec printenv NODE_ENV || echo "")
  if [[ "$RENDERER_NODE_ENV" == "production" ]]; then
    pass "renderer-api runs with NODE_ENV=production"
  else
    fail "renderer-api NODE_ENV is '$RENDERER_NODE_ENV', expected production"
  fi

  RENDERER_TRUSTED_ORIGINS=$(renderer_exec printenv AUTH_TRUSTED_ORIGINS || echo "")
  if [[ "$RENDERER_TRUSTED_ORIGINS" == https://* ]]; then
    pass "AUTH_TRUSTED_ORIGINS is HTTPS ($RENDERER_TRUSTED_ORIGINS) while NODE_ENV=production — no HTTP-origin exception was added"
  else
    fail "AUTH_TRUSTED_ORIGINS is not HTTPS: $RENDERER_TRUSTED_ORIGINS"
  fi

  # Gateway TLS certificate validates against the generated CA (curl below
  # uses the wrapped `curl` function, which passes --cacert "$CACERT" —
  # never -k/--insecure; a cert mismatch would fail this and every other
  # curl call in this script, not just this one).
  GATEWAY_TLS_STATUS=$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 --max-time 10 "$API_URL/readyz" 2>/dev/null || echo "000")
  if [[ "$GATEWAY_TLS_STATUS" == "200" ]]; then
    pass "Gateway TLS certificate validates against the generated CA (/readyz via HTTPS returns 200)"
  else
    fail "Gateway HTTPS /readyz returned $GATEWAY_TLS_STATUS with CA verification enabled"
  fi

  # renderer-api must not publish a host port directly in this profile —
  # the gateway is the only way in.
  RENDERER_CONTAINER_ID=$(get_container_id "$RENDERER_SERVICE")
  RENDERER_PORTS=$(docker inspect "$RENDERER_CONTAINER_ID" | jq -r '.[0].HostConfig.PortBindings // {} | keys[]' 2>/dev/null || echo "")
  if [[ -z "$RENDERER_PORTS" ]]; then
    pass "renderer-api publishes no host port in the TLS profile"
  else
    fail "renderer-api has published ports in the TLS profile: $RENDERER_PORTS"
  fi

  # Gateway itself must publish only the TLS port, bound to loopback.
  GATEWAY_CONTAINER_ID=$(get_container_id "$GATEWAY_SERVICE")
  GATEWAY_PORT_BINDINGS=$(docker inspect "$GATEWAY_CONTAINER_ID" | jq -c '.[0].HostConfig.PortBindings // {}' 2>/dev/null || echo "{}")
  if echo "$GATEWAY_PORT_BINDINGS" | jq -e '."443/tcp"[0].HostIp == "127.0.0.1"' > /dev/null 2>&1; then
    pass "Gateway TLS port is bound to 127.0.0.1 only"
  else
    fail "Gateway port binding unexpected: $GATEWAY_PORT_BINDINGS"
  fi
  if echo "$GATEWAY_PORT_BINDINGS" | jq -e '. | length == 1' > /dev/null 2>&1; then
    pass "Gateway publishes exactly one host port (no plain-HTTP port published — HTTP access is unavailable, not just redirected)"
  else
    fail "Gateway publishes unexpected extra ports: $GATEWAY_PORT_BINDINGS"
  fi

  # Real cookie-jar HTTPS login/session/logout flow, against the same
  # bootstrapped owner as above but through the TLS gateway origin. Uses
  # curl's own cookie jar (-c/-b) end to end — never manually copying a
  # Secure cookie into a plain-HTTP header, which would bypass the exact
  # browser behavior being verified here.
  TLS_COOKIE_JAR="$(mktemp)"
  TLS_LOGIN_HEADERS=$(curl -s -D - -o /dev/null -c "$TLS_COOKIE_JAR" --connect-timeout 5 --max-time 10 \
    -X POST "$API_URL/api/auth/sign-in/email" \
    -H "content-type: application/json" \
    -d "{\"email\":\"$BOOTSTRAP_OWNER_EMAIL\",\"password\":\"$BOOTSTRAP_OWNER_PASSWORD\"}" 2>/dev/null || echo "")
  SET_COOKIE_LINE=$(echo "$TLS_LOGIN_HEADERS" | grep -i '^set-cookie:' | grep -i session_token || echo "")
  if echo "$SET_COOKIE_LINE" | grep -qi 'Secure' && \
     echo "$SET_COOKIE_LINE" | grep -qi 'HttpOnly' && \
     echo "$SET_COOKIE_LINE" | grep -qi 'SameSite=Lax' && \
     echo "$SET_COOKIE_LINE" | grep -qi 'Path=/'; then
    pass "Session cookie over HTTPS has Secure, HttpOnly, SameSite=Lax, Path=/"
  else
    fail "Session cookie over HTTPS missing expected flags: $SET_COOKIE_LINE"
  fi
  if echo "$SET_COOKIE_LINE" | grep -qi 'Domain='; then
    fail "Session cookie sets a Domain attribute (should be host-only)"
  else
    pass "Session cookie has no Domain attribute (host-only)"
  fi

  TLS_ORG_LIST=$(curl -sf -b "$TLS_COOKIE_JAR" --connect-timeout 5 --max-time 10 "$API_URL/v1/organizations" 2>/dev/null || echo '{}')
  if echo "$TLS_ORG_LIST" | jq -e '.items | length > 0' > /dev/null 2>&1; then
    pass "Authenticated organization-scoped request succeeds over HTTPS using the cookie jar"
  else
    fail "Authenticated HTTPS request failed: $(echo "$TLS_ORG_LIST" | head -c 200)"
  fi

  curl -s -o /dev/null -b "$TLS_COOKIE_JAR" --connect-timeout 5 --max-time 10 -X POST "$API_URL/api/auth/sign-out" > /dev/null 2>&1 || true
  TLS_LOGGED_OUT_STATUS=$(curl -s -o /dev/null -w '%{http_code}' -b "$TLS_COOKIE_JAR" --connect-timeout 5 --max-time 10 "$API_URL/v1/organizations" 2>/dev/null || echo "000")
  if [[ "$TLS_LOGGED_OUT_STATUS" == "401" ]]; then
    pass "Session cookie no longer authenticates after HTTPS logout"
  else
    fail "Post-logout HTTPS request returned $TLS_LOGGED_OUT_STATUS, expected 401"
  fi
  rm -f "$TLS_COOKIE_JAR"

  # Gateway and renderer-api logs must never contain API keys, cookies, or
  # certificate private key material.
  GATEWAY_LOGS=$(compose logs "$GATEWAY_SERVICE" 2>/dev/null || echo "")
  if echo "$GATEWAY_LOGS$RENDERER_LOGS" | grep -qF "$SET_COOKIE_LINE" && [[ -n "$SET_COOKIE_LINE" ]]; then
    fail "Container logs contain the raw session cookie"
  else
    pass "Container logs do not contain the raw session cookie"
  fi
  if echo "$GATEWAY_LOGS" | grep -q -- '-----BEGIN'; then
    fail "Gateway logs contain PEM key/certificate material"
  else
    pass "Gateway logs do not contain PEM key/certificate material"
  fi
fi

# ---- Summary ----
section "Summary"
echo "  PASSED: $PASS"
echo "  FAILED: $FAIL"

if [[ $FAIL -gt 0 ]]; then
  echo ""
  echo "  Failed tests:"
  for err in "${ERRORS[@]}"; do
    echo "    - $err"
  done
  exit 1
fi

echo ""
echo "  All security smoke tests passed."
exit 0
